# 日志配置
logConfig:
  logDir: ./log
  appName: hddcoin_monitor
  logSaveDay: 7
  isProduction: true

# 币种信息
coin:
  name: hddcoin
  blockChainRpcUrl: "https://127.0.0.1:28555/"
  walletRpcUrl: "https://127.0.0.1:29256/"
  farmerRpcUrl: "https://127.0.0.1:28559/"

# 全节点证书路径
fullNodeCertPath:
  certPath: ssl/full_node/private_full_node.crt
  keyPath: ssl/full_node/private_full_node.key

# 钱包证书路径
walletCertPath:
  certPath: ssl/wallet/private_wallet.crt
  keyPath: ssl/wallet/private_wallet.key

# 监控配置，时间间隔单位：分钟
monitor:
  machineName: NAS
  blockChainInterval: 10
  farmerInterval: 5
  dailyCron: "0 58 11 * * *"
  harvesterList: [ "home.yasin.store","221.229.116.142","lj.yasin.store" ]
  harvesterOfflineFlag: "./.harvesterOfflineFlag"
  isSupportPool: false
