# 日志配置
logConfig:
  logDir: ./log
  appName: chia_monitor
  logSaveDay: 30
  isProduction: false

# 全节点证书路径
fullNodeCertPath:
  certPath: ssl/full_node/private_full_node.crt
  keyPath: ssl/full_node/private_full_node.key

# 钱包证书路径
walletCertPath:
  certPath: ssl/wallet/private_wallet.crt
  keyPath: ssl/wallet/private_wallet.key

# 监控配置，时间间隔单位：分钟
monitor:
  machineName: NAS
  blockChainInterval: 10
  farmerInterval: 5
  walletCron: "0 57 11 * * *"
  harvesterList: [ "127.0.0.1","221.229.116.134","221.229.116.142","221.229.116.130","lj.yasin.store" ]